### ISSUE TITLE
maker current location 

### ISSUE THREAD

**Issue by knack000** [bradcornford/Googlmapper#205] opened 2017-10-20 10:28 UTC
Mapper::map(0, 0, ['locate' => true, 'marker' => true]);

it maker at 0,0 
how can i maker at current location

thank you.

**Comment by bradcornford** [comment] 2017-10-24 09:48
Hi there,

The below should ask the device for its current location, which should work for you. Bare in mind that if the user denies the location request it will fall back to the maps set location:

```php
Mapper::map(0, 0, ['locate' => true, 'marker' => true, 'locate' => true]);
```

**Comment by bradcornford** [comment] 2017-10-24 10:03
Actually, i think i understand your issue, the markers isn't at the current location, but the maps set location. I'll looking putting a fix together for this.

**Comment by bradcornford** [comment] 2017-10-24 10:26
This issue should now be resolved in current version 2.28.2/1.23.2.

**Closed by bradcornford** 2017-10-24 10:26 UTC
Labels: bug

**Comment by jomayan** [comment] 2017-12-10 06:55
I tried this with my code below.. and the marker is at 0,0 . but the map centers at my current location.

`Mapper::map(0, 0, ['marker' => true, 'locate' => true, 'animation' => 'DROP','eventAfterLoad' => 'loadMarkerOverlay(map);','zoom' => 12, 'icon' => '../images/blank50.jpg' ]); `

**Comment by bradcornford** [comment] 2018-01-12 15:34
Hi,

Did you try this on the latest version of the package?

**Comment by jomayan** [comment] 2018-01-12 15:51
yes, I used the latest version of the package.

**Comment by bradcornford** [comment] 2018-01-17 10:12
This is working for me, have you allowed the browser to use your location?

**Comment by bradcornford** [comment] 2018-01-17 10:12
<img width="1064" alt="screen shot 2018-01-17 at 10 11 43" src="https://user-images.githubusercontent.com/2913887/35037251-f322c724-fb6e-11e7-9463-4c8e09c494f5.png">

**Comment by jomayan** [comment] 2018-01-17 10:21
I really don't understand. Even if i use `Mapper::map(0, 0, ['locate' => true, 'marker' => true]);` this code.
It just leaves the marker at 0,0 then go to my current location.

**Comment by bradcornford** [comment] 2018-01-17 10:34
For me, the map initially loads at 0,0 with a maker, however once the location has been reported by the browser the map and marker both move to the current location.

**Comment by jomayan** [comment] 2018-01-17 10:37
The same as mine, initially it loads at 0,0 with the marker then the map moves to my current location but the marker is left at 0,0.

**Comment by bradcornford** [comment] 2018-01-17 10:41
Can you try running `composer update` and `php artisan vendor:publish --provider="Cornford\Googlmapper\MapperServiceProvider" --tag=googlmapper`

**Comment by jomayan** [comment] 2018-01-17 10:52
I run both commands.
It's now updated  to v2.30.0 .
Still the same. I can't upload a video here, i uploaded it here https://youtu.be/Hu5O46iOVhw  so you can see..

**Comment by bradcornford** [comment] 2018-01-17 10:57
That is strange, can you try just the following, with nothing else:

```php
Mapper::map(0, 0, ['locate' => true, 'icon' => 'https://drainz.uk/wp-content/uploads/2015/05/map_marker.png']);
```

**Comment by jomayan** [comment] 2018-01-17 11:01
I used the code `Mapper::map(0, 0, ['locate' => true, 'icon' => 'https://drainz.uk/wp-content/uploads/2015/05/map_marker.png']);`.  and nothing else..

Still the same...

<img width="1464" alt="screen shot 2018-01-17 at 2 59 16 am" src="https://user-images.githubusercontent.com/25026077/35039384-8ef1e050-fb32-11e7-8d5d-ea45e5360ea7.png">

**Comment by bradcornford** [comment] 2018-01-17 11:08
What browser are you using? Have you changed any default configuration values in `googlmapper.php`?

**Comment by jomayan** [comment] 2018-01-17 11:13
I'm using Chrome, Safari and Firefox...

Here's my googlemapper.php (removed the comments)

`<?php

return array(
    'enabled' => true,
    'key' => env('GOOGLE_API_KEY', '--removed--'),
    'region' => 'US',
    'language' => 'en-us',
    'async' => false,
    'user' => false,
    'marker' => true,
    'center' => true,
    'locate' => false,
    'zoom' => 11,
    'scrollWheelZoom' => true,
    'zoomControl' => true,
    'mapTypeControl' => true,
    'scaleControl' => false,
    'streetViewControl' => true,
    'rotateControl' => false,
    'fullscreenControl' => true,
    'type' => 'ROADMAP',
    'ui' => true,
    'markers' => array(
        'icon' => 'http://maps.google.com/mapfiles/ms/icons/red-dot.png',
        'animation' => 'DROP',
    ),

    'cluster' => true,
    'clusters' => array (
        'icon' => '//googlemaps.github.io/js-marker-clusterer/images/m',
        'grid' => 60,
        'zoom' => null,
        'center' => false,
        'size' => 2

    ),

);
`

**Comment by bradcornford** [comment] 2018-01-17 11:26
Okay, so the functionality works in Chrome, but not Safari and FireFox. Are you utilising https for the connection to your site?

I tried testing the browsers for compatibility with: https://www.w3schools.com/html/tryit.asp?filename=tryhtml5_geolocation

Then they worked after that. This is rather odd!

**Comment by jomayan** [comment] 2018-01-17 11:34
I really dont know why it doesnt work on mine (all browsers).
Yes, my site is utilizing HTTPS .

I also tried this one : https://www.w3schools.com/html/tryit.asp?filename=tryhtml5_geolocation 
But it still the same.

This is so weird, i'm not sure if its just me having this problem.

**Comment by bradcornford** [comment] 2018-01-17 11:47
The only other thing i can suggest is to hook your own event, something like this (At least you might be able to debug this more easily):

```php
Mapper::map(0, 0, ['eventAfterLoad' => 'attachMapListeners(map);', 'locate' => true]);
```

```html
function attachMapListeners(map)
        {
            map.addListener('center_changed', function() {
                setTimeout(function () {
                    console.log('center_changed');
                    if (typeof navigator !== 'undefined' && navigator.geolocation) {
                        navigator.geolocation.getCurrentPosition(function (position) {
                            maps[0].markers[0].setPosition(new google.maps.LatLng(position.coords.latitude, position.coords.longitude));
                        });
                    }
                }, 200);
            });
        }
```

**Comment by jomayan** [comment] 2018-01-17 11:49
ok, I'll try this out..

Thank you so much for your time @bradcornford  . I really appreciate it 👍

**Comment by jomayan** [comment] 2018-01-18 00:00
I used your function and it works... the marker moved to my current location.

**Comment by bradcornford** [comment] 2018-02-05 09:22
Excellent. I'm not sure what the issue is, i assume its something to do with needing a timeout before trying to move the marker. I will look at setting this up within the map itself, as the above was taken from the library itself.
